spring:
  application.name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/events_rik
    username: postgres
    password: root
  jpa.hibernate.ddl-auto: update
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    log-resolved-exception: true

payment:
  types:
    - BANK_TRANSFER
    - CASH